@Demo_HostAddress = http://localhost:5045

GET {{Demo_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Demo_HostAddress}}/counter/
Accept: application/json

### expire appcounter key
GET {{Demo_HostAddress}}/appkeyexpire/
Accept: application/json

### app only test
GET {{Demo_HostAddress}}/apponly
Accept: application/json

### counter and application test
GET {{Demo_HostAddress}}/counterwithapp/
Accept: application/json